channel_conf:
  - FP1-F3
  - F3-C3
  - C3-P3
  - P3-O1
  - FP1-F7
  - F7-T3
  - T3-T5
  - T5-O1
  - FP2-F4
  - F4-C4
  - C4-P4
  - P4-O2
  - FP2-F8
  - F8-T4
  - T4-T6
  - T6-O2
  - FZ-CZ
  - CZ-PZ
sampling_rate: 256
notch_filter: 50
filter:
  - 0.5
  - 45
normalize: true
window: 10
batch_size: 32
event_annotation:
  - background
  - artifact
  - generalized_epileptiform_discharge